In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("Dataset\dataset.csv")

In [8]:
df.head(5)

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB


In [10]:
df.describe()

id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [12]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [13]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

## Feature Selection

In [26]:
 df = df[['id','title','overview','genre']]

In [27]:
df.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                            overview                 genre  
0  Framed in the 1940s for the double murder of h...           Drama,Crime  
1  Raj is a rich, carefree, happy-go-lucky second...  Comedy,Drama,Romance  
2  Spanning the years 1945 to 1955, a chronicle o...           Drama,Crime  
3  The true story of how businessman Oskar Schind...     Drama,History,War  
4  In the continuing saga of the Corleone crime f...           Drama,Crime

In [28]:
df['tags'] = df['overview'] + df['genre']

In [29]:
df.head(10)

id                        title  \
0     278     The Shawshank Redemption   
1   19404  Dilwale Dulhania Le Jayenge   
2     238                The Godfather   
3     424             Schindler's List   
4     240       The Godfather: Part II   
5  667257            Impossible Things   
6     129                Spirited Away   
7  730154               Your Eyes Tell   
8  372754     Dou kyu sei – Classmates   
9  372058                   Your Name.   

                                            overview  \
0  Framed in the 1940s for the double murder of h...   
1  Raj is a rich, carefree, happy-go-lucky second...   
2  Spanning the years 1945 to 1955, a chronicle o...   
3  The true story of how businessman Oskar Schind...   
4  In the continuing saga of the Corleone crime f...   
5  Matilde is a woman who, after the death of her...   
6  A young girl, Chihiro, becomes trapped in a st...   
7  A tragic accident lead to Kaori's blindness, b...   
8  Rihito Sajo, an honor student with a perfect s...   
9  High schoolers Mitsuha and Taki are complete s...   

                      genre                                               tags  
0               Drama,Crime  Framed in the 1940s for the double murder of h...  
1      Comedy,Drama,Romance  Raj is a rich, carefree, happy-go-lucky second...  
2               Drama,Crime  Spanning the years 1945 to 1955, a chronicle o...  
3         Drama,History,War  The true story of how businessman Oskar Schind...  
4               Drama,Crime  In the continuing saga of the Corleone crime f...  
5              Family,Drama  Matilde is a woman who, after the death of her...  
6  Animation,Family,Fantasy  A young girl, Chihiro, becomes trapped in a st...  
7             Romance,Drama  A tragic accident lead to Kaori's blindness, b...  
8         Romance,Animation  Rihito Sajo, an honor student with a perfect s...  
9   Romance,Animation,Drama  High schoolers Mitsuha and Taki are complete s...

In [30]:
data = df.drop(columns=['overview','genre'])

In [31]:
data.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                                tags  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

In [32]:
data.shape

(10000, 3)

In [33]:
# now convert text to vector 
# 1.bag of word 
# 2. TFIDF

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
cv = CountVectorizer(max_features=10000,stop_words='english')

In [36]:
vec = cv.fit_transform(data['tags'].values.astype('U')).toarray()

In [37]:
vec.shape

(10000, 10000)

In [38]:
# cosine similarity

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
similarity = cosine_similarity(vec)

In [41]:
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
vec[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
data.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                                tags  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

In [46]:
data[data['title'] == "The Shawshank Redemption"].index[0]

0

In [48]:
data[data['title'] == "Dilwale Dulhania Le Jayenge"].index[0]

1

In [49]:
similarity[1]

array([0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
       0.        ])

In [50]:
list(enumerate(similarity[1]))

[(0, 0.0563436169819011),
 (1, 1.0000000000000002),
 (2, 0.07624928516630233),
 (3, 0.036369648372665396),
 (4, 0.1126872339638022),
 (5, 0.041666666666666664),
 (6, 0.07453559924999298),
 (7, 0.08006407690254357),
 (8, 0.026688025634181187),
 (9, 0.06950480468569159),
 (10, 0.0944911182523068),
 (11, 0.1),
 (12, 0.1386750490563073),
 (13, 0.029462782549439476),
 (14, 0.06085806194501845),
 (15, 0.02457365935914952),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.125),
 (20, 0.14213381090374028),
 (21, 0.16169041669088863),
 (22, 0.0314970394174356),
 (23, 0.06666666666666667),
 (24, 0.08084520834544431),
 (25, 0.1178511301977579),
 (26, 0.04042260417272216),
 (27, 0.07453559924999299),
 (28, 0.03268602252303067),
 (29, 0.10206207261596575),
 (30, 0.07106690545187014),
 (31, 0.030429030972509225),
 (32, 0.03553345272593507),
 (33, 0.03333333333333333),
 (34, 0.025717224993681984),
 (35, 0.0),
 (36, 0.048112522432468816),
 (37, 0.08606629658238703),
 (38, 0.048112522432468816),
 (39, 0.032

In [53]:
distance = sorted(list(enumerate(similarity[1])),reverse=True,key=lambda vec:vec[1])

In [54]:
for i in distance[1:6]:
    print(data.iloc[i[0]].title)

A Passage to India
The Manual of Love
The Cameraman
The Graduate
A California Christmas


In [55]:
rec_movies = [data.iloc[i[0]].title for i in distance[1:6]]

In [56]:
rec_movies

['A Passage to India',
 'The Manual of Love',
 'The Cameraman',
 'The Graduate',
 'A California Christmas']

In [57]:
def recommendation(movies):
    index = data[data['title'] == movies].index[0]
    distance = sorted(list(enumerate(similarity[index])),reverse=True,key=lambda vec:vec[1])
    rec_movies = [data.iloc[i[0]].title for i in distance[1:6]]
    return rec_movies

In [58]:
recommendation("A Passage to India")

['Gandhi',
 'Life of Pi',
 'Victoria & Abdul',
 'Dilwale Dulhania Le Jayenge',
 "The World's Fastest Indian"]

In [59]:
import pickle

In [61]:
pickle.dump(data, open('movies_list.pkl', 'wb'))

In [62]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))